fix(model): #CRRE-550 upgrade model to take joins into account
CGI-OPEN-ENT-NG/crre pull request #104
Opened 2023-03-30 14:57 UTC by BastienBenard

## Describe your changes

## Checklist tests

## Issue ticket number and link

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-03-30 15:22 UTC, BastienBenard commented on src/main/resources/sql/017-crre-550-group-order-table-in-one-view.sql
Ajout de order_client_id et order_region_id

2023-03-30 15:56 UTC, flmartineau approved these changes

2023-03-30 15:56 UTC, flmartineau commented on src/main/java/fr/openent/crre/controllers/CampaignController.java
> +                    log.error(" An error occurred when casting campaign id", e);
Ajoute [CampaignController@%s::create] pour être plus clair dans le log.

2023-03-30 15:56 UTC, flmartineau commented on src/main/java/fr/openent/crre/controllers/CampaignController.java
> +                    log.error(" An error occurred when casting campaign id", e);
Pareil

2023-03-30 16:33 UTC, BastienBenard commented on src/main/java/fr/openent/crre/controllers/CampaignController.java
> +                    log.error(" An error occurred when casting campaign id", e);
J'ai pas mis de réponse en plus

2023-03-31 07:50 UTC, JinDouang requested changes

2023-03-31 07:50 UTC, JinDouang commented on src/main/java/fr/openent/crre/controllers/CampaignController.java
> +        RequestUtils.bodyToJson(request, pathPrefix + "campaign", campaign -> {
lambda

2023-03-31 07:50 UTC, JinDouang commented on src/main/java/fr/openent/crre/controllers/CampaignController.java
> +                    log.error(String.format("[CRRE@%s::create] Fail to create campaign %s"),
Attention ton string format est mal géré 

Aussi, tu ne devrais pas mettre `e.getMessage()` ?

2023-03-31 07:50 UTC, JinDouang commented on src/main/java/fr/openent/crre/controllers/CampaignController.java
> +                    log.error(String.format("[CRRE@%s::update] Fail to update campaign %s"),
Attention ton string format est mal géré

Aussi, tu ne devrais pas mettre e.getMessage() ?

2023-03-31 09:42 UTC, JinDouang approved these changes

2023-03-31 09:43 UTC, merged