Crre 465
CGI-OPEN-ENT-NG/crre pull request #38
Opened 2023-01-26 14:19 UTC by BastienBenard

## Describe your changes

## Checklist tests

## Issue ticket number and link

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-01-27 11:15 UTC, BastienBenard commented on src/main/java/fr/openent/crre/helpers/elasticsearch/ElasticSearch.java
> +		if ((serverUris == null || serverUris.isEmpty()) && serverUri != null) {
serverUris ne peut plus être null avec le ConfigModel mais il peut être vide

2023-01-27 11:15 UTC, BastienBenard commented on src/main/java/fr/openent/crre/model/config/ConfigElasticSearch.java
> +        this.serverUris = jsonObject.getJsonArray(ConfigField.SERVER_DASH_URIS, new JsonArray()).stream()
Évite un NPE

2023-01-27 11:15 UTC, BastienBenard commented on src/main/resources/public/ts/model/StructureGroup.ts
> -        });
L'API retourne directement un JsonArray maintenant

2023-01-27 11:15 UTC, BastienBenard commented on src/main/java/fr/openent/crre/service/impl/DefaultStructureGroupService.java
> +        structureService.insertStudentsInfos(new JsonArray(new ArrayList<>(structures)), event -> {
Ce sera fait lors de la refacto de structureService

2023-01-27 16:50 UTC, sjollois approved these changes

2023-01-30 09:33 UTC, qpic-cgi requested changes

2023-01-30 09:33 UTC, qpic-cgi commented on src/main/java/fr/openent/crre/helpers/IModelHelper.java
> +                if (errorMessage != null) {
Donc si tu n'as pas de message tu ne log rien ?
Ca me parait dangereux quand même.

2023-01-30 09:33 UTC, qpic-cgi commented on src/main/java/fr/openent/crre/service/impl/DefaultStructureGroupService.java
> +                    String errorMessage = String.format("An error occurred when launching transaction from %s::create", this.getClass().getSimpleName());
flag sur ton erreur

2023-01-30 09:33 UTC, qpic-cgi commented on src/main/java/fr/openent/crre/service/impl/DefaultStructureGroupService.java
> +                    String errorMessage = String.format("An error occurred when launching transaction from %s::update", this.getClass().getSimpleName());
flag sur ton erreur

2023-01-30 09:33 UTC, qpic-cgi commented on src/main/java/fr/openent/crre/service/impl/DefaultStructureGroupService.java
> +        String errorMessage = String.format("An error occurred when launching transaction from %s::delete", this.getClass().getSimpleName());
flag

2023-01-31 10:38 UTC, BastienBenard commented on src/main/java/fr/openent/crre/helpers/IModelHelper.java
> +                if (errorMessage != null) {
C'est voulu, le développeur en question peut ne pas vouloir de log par cette fonction car il peut avoir une gestion des logs lorsque la promise fail a un autre endroit.

2023-01-31 13:00 UTC, qpic-cgi approved these changes

2023-02-02 08:00 UTC, merged