Crre 423
CGI-OPEN-ENT-NG/crre pull request #43
Opened 2023-02-03 15:10 UTC by BastienBenard

## Describe your changes

## Checklist tests

## Issue ticket number and link

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-02-06 14:13 UTC, qpic-cgi requested changes

2023-02-06 14:13 UTC, qpic-cgi commented on src/main/java/fr/openent/crre/controllers/OrderRegionController.java
> +                    equipment.put(Field.PRICE, priceTTC);
t'aurais pu faire ça dans ton map je pense, au lieu de refaire un foreach par dessus (ici en soit, tu boucles 2 fois, alors que tu pourrais ne boucler qu'une fois).

2023-02-06 14:13 UTC, qpic-cgi commented on src/main/java/fr/openent/crre/controllers/OrderRegionController.java
> +                });
pareil ici, tu pourrais faire ça dans ton map je pense !
D'ailleur si tu ne retournes rien, n'utilise pas de map et utilise qu'un forEach directement.
A toi de voir !

2023-02-06 14:13 UTC, qpic-cgi commented on src/main/java/fr/openent/crre/logging/Logging.java
> +                .map(jsonObject -> addTransaction(context, action, item, jsonObject, userInfos))
tu ne peux pas tout mettre dans ton premier map ?

2023-02-06 16:41 UTC, BastienBenard commented on src/main/java/fr/openent/crre/controllers/OrderRegionController.java
> +                    equipment.put(Field.PRICE, priceTTC);
Je fais cela pour eviter de faire des casts. Mais effectivement il faudrait utiliser des listes de model plustot que un JsonArray. Ce sera fait a un moment dans le ticket de refactor [CRRE-453](https://jira.support-ent.fr/browse/CRRE-453)

2023-02-06 16:42 UTC, BastienBenard commented on src/main/java/fr/openent/crre/controllers/OrderRegionController.java
> +                });
même réponse

2023-02-06 16:42 UTC, BastienBenard commented on src/main/java/fr/openent/crre/logging/Logging.java
> +                .map(jsonObject -> addTransaction(context, action, item, jsonObject, userInfos))
même réponse

2023-02-07 08:34 UTC, qpic-cgi approved these changes

2023-02-07 10:30 UTC, merged