refactor:
CGI-OPEN-ENT-NG/crre pull request #45
Opened 2023-02-07 08:30 UTC by BastienBenard

## Describe your changes

## Checklist tests

## Issue ticket number and link

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-02-08 10:17 UTC, qpic-cgi requested changes

2023-02-08 10:17 UTC, qpic-cgi commented on src/main/java/fr/openent/crre/service/impl/DefaultBasketOrderItemService.java
> +        values.add(idCampaign).add(idStructure).add(user.getUserId());
Je ne sais pas ce que tu en penses ici, mais tes params ne sont pas des primitives, du coup tu peux avoir des params null techniquement.

2023-02-08 10:17 UTC, qpic-cgi commented on src/main/java/fr/openent/crre/service/impl/DefaultBasketOrderItemService.java
> +        params.add(user.getUserId());
même potentiel pb ici

2023-02-08 10:17 UTC, qpic-cgi commented on src/main/java/fr/openent/crre/service/impl/DefaultBasketOrderService.java
> +        values.add(startDate).add(endDate).add(user.getUserId()).add(idCampaign);
pareil ici

2023-02-08 10:17 UTC, qpic-cgi commented on src/main/java/fr/openent/crre/service/impl/DefaultBasketOrderService.java
> +        values.add(startDate).add(endDate).add(user.getUserId()).add(idCampaign);
ici aussi

2023-02-09 09:02 UTC, BastienBenard commented on src/main/java/fr/openent/crre/service/impl/DefaultBasketOrderItemService.java
> +        values.add(idCampaign).add(idStructure).add(user.getUserId());
Pour ce qui est de idCampaign et idStructure ce n'est pas grave. S'il sont null la requête SQL ne retournera aucun information. Pour contre tu as raison pour le userInfo je vais changer cela.

2023-02-09 09:05 UTC, BastienBenard commented on src/main/java/fr/openent/crre/service/impl/DefaultBasketOrderItemService.java
> +        params.add(user.getUserId());
Pour id je vais le passer en primitif, pour les 2 autres s'il sont null on veut bien que un NPE soit levé

2023-02-09 09:06 UTC, BastienBenard commented on src/main/java/fr/openent/crre/service/impl/DefaultBasketOrderService.java
> +        values.add(startDate).add(endDate).add(user.getUserId()).add(idCampaign);
Pour ce qui est des primitif ce n'est pas grave. S'il sont null la requête SQL ne retournera aucun information. Par contre tu as raison pour le userInfo je vais changer cela.

2023-02-09 09:11 UTC, BastienBenard commented on src/main/java/fr/openent/crre/service/impl/DefaultBasketOrderService.java
> +        values.add(startDate).add(endDate).add(user.getUserId()).add(idCampaign);
Ici aussi on veut bien levé des NPE si les paramettre sont null. Pour autant si l'utilisateur n'est dans aucune structure cela va généré un requête sql non valide.

2023-02-09 09:13 UTC, qpic-cgi approved these changes

2023-02-09 09:13 UTC, merged