Crre 480
CGI-OPEN-ENT-NG/crre pull request #51
Opened 2023-02-16 08:32 UTC by BastienBenard

## Describe your changes

## Checklist tests

## Issue ticket number and link

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-02-20 15:15 UTC, qpic-cgi approved these changes

2023-02-20 15:15 UTC, qpic-cgi commented on src/main/java/fr/openent/crre/service/impl/DefaultNotificationService.java
> +            }
Je ne comprend pas ici le faite de laisser un catch vide.

2023-02-20 15:15 UTC, qpic-cgi commented on src/main/java/fr/openent/crre/service/impl/DefaultNotificationService.java
> +            }
CF, commentaire au dessus

2023-02-21 10:48 UTC, Sofianebernoussi commented on src/main/java/fr/openent/crre/controllers/OrderRegionController.java
> +        if ("REJECTED".equals(orderRegion.getStatus())) {
t'as créer un enum pour le rejected je crois autant l'utiliser

2023-02-21 10:48 UTC, Sofianebernoussi commented on src/main/java/fr/openent/crre/model/neo4j/Neo4jUserDataModel.java
> +public class Neo4jUserDataModel implements IModel<Neo4jUserDataModel> {
la classe userinfo peut être utiliser a la lmite l'extend

2023-02-21 10:48 UTC, Sofianebernoussi commented on src/main/java/fr/openent/crre/model/neo4j/Neo4jUserModel.java
> +public class Neo4jUserModel implements IModel<Neo4jUserModel> {
pareil

2023-02-21 14:26 UTC, sjollois approved these changes

2023-02-22 10:51 UTC, JinDouang commented on src/main/resources/view-src/notify/new_notification.html
> +<div class="crre-timeline-new-notification">
Je te fais un commentaire côté css : https://github.com/CGI-OPEN-ENT-NG/entcore-css-lib/pull/32/files#diff-14afd4688fa684781c4f1e209b9e21a1e00e646f65f50b07c82fcf9a76693f78R1

2023-02-22 13:35 UTC, BastienBenard commented on src/main/java/fr/openent/crre/service/impl/DefaultNotificationService.java
> +            }
S'il y a une erreur je n'ai pas besoin de faire autre chose. Je peux faire ça mais cela reviens au meme
```suggestion
            String local;
            try {
                local = new JsonObject((String) ((LinkedHashMap<?, ?>) userInfos.getAttribute(Field.PREFERENCES)).get(Field.LANGUAGE)).getString(Field.DEFAULT_DASH_DOMAIN);
            } catch (Exception ignored) {
                local = null;
            }
```

2023-02-22 13:52 UTC, qpic-cgi commented on src/main/java/fr/openent/crre/service/impl/DefaultNotificationService.java
> +            }
tu ne peux pas enlever le try du coup ?

2023-02-22 14:09 UTC, BastienBenard commented on src/main/java/fr/openent/crre/service/impl/DefaultNotificationService.java
> +            }
non car s'il y a un exception telque un CastException, oon ne va pas envoyer la notification

2023-02-23 09:34 UTC, BastienBenard commented on src/main/resources/view-src/notify/new_notification.html
> +<div class="crre-timeline-new-notification">
Vu avec Jin et Laurie, ce n'est plus d'actualiter. On ne veut pas de logo custom.

2023-02-23 13:01 UTC, JinDouang requested changes

2023-02-23 15:04 UTC, BastienBenard commented on src/main/java/fr/openent/crre/service/impl/DefaultUserService.java
> +                " return distinct u,s.id";
Le data ne sert a rien dans Neo4jUserModel, je vais le supprimer. Pour le coups je laisse u dans le cas on l'on aurait besoin de plus d'information pour les futures dev

2023-02-23 15:10 UTC, Sofianebernoussi approved these changes

2023-02-23 15:13 UTC, JinDouang approved these changes

2023-02-23 15:22 UTC, merged