feat: #CRRE-486 filter orders selection through some admin actions
CGI-OPEN-ENT-NG/crre pull request #78
Opened 2023-03-14 17:50 UTC by sjollois

## Describe your changes
Filter sent or refused orders when the admin refused, validate or sent the orders to the library. Disable the buttons "send to the library" when the filter "sent to the library" is checked
## Checklist tests
Check "Sent to the library" filter and the buttons must be disabled.
if you try to sent orders that already be"sent to the library", they will be filtered.
## Issue ticket number and link
[https://jira.support-ent.fr/browse/CRRE-486](url)
## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [x] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-03-15 09:08 UTC, Rseuret requested changes

2023-03-15 09:08 UTC, Rseuret commented on src/main/resources/public/template/administrator/order/order-waiting.html
> +                            ng-disabled="checkStatusChoice('SENT')">
t'as une enum plus loin avec la liste des statuts tu pourrais l'utiliser ici non ?

2023-03-15 11:07 UTC, sjollois commented on src/main/resources/public/template/administrator/order/order-waiting.html
> +                            ng-disabled="checkStatusChoice('SENT')">
mais il ne le prend pas en compte dans le HTML ou alors tu as une idée de comment faire ?

2023-03-15 14:34 UTC, Rseuret commented on src/main/resources/public/template/administrator/order/order-waiting.html
> +                            ng-disabled="checkStatusChoice('SENT')">
tu peux le mettre dans une constant dans ton controller et l'appeler dans l html je pense

2023-03-16 08:38 UTC, BastienBenard approved these changes

2023-03-16 08:38 UTC, BastienBenard commented on src/main/resources/public/ts/model/OrderRegion.ts
> +            filteredOrder.forEach(order => params_id_structure.add(order.id_structure));
typage du paramètre order dans les lambda

2023-03-21 09:30 UTC, Sofianebernoussi approved these changes

2023-03-22 10:27 UTC, merged